/**
 * main.js — Entry point
 * Loads all components, injects CSS, and initialises all modules.
 *
 * ─── SHARED GOOGLE SHEETS SETUP ──────────────────────────────────────────────
 *
 * All three features (RSVP, Guestbook, Gallery) share ONE Google Sheets
 * workbook and ONE Apps Script Web App deployment.
 *
 * Step 1 — Create the workbook
 *   Open Google Sheets and create a new spreadsheet.
 *   Add three sheets (tabs) named exactly:
 *     • RSVP
 *     • Guestbook
 *     • Gallery
 *
 *   Column headers (row 1) for each tab:
 *
 *   RSVP:      Timestamp | Name | Phone | Attendance | Guests | Dietary | Message
 *   Guestbook: Timestamp | ID | Name | Message | Likes | LikedBy
 *   Gallery:   Timestamp | Category | ImageUrl
 *
 *   Notes:
 *   - ID = random short hash generated by the browser (e.g. "a3f9c2b1")
 *   - Likes = number (default 0)
 *   - LikedBy = comma-separated device IDs (default empty)
 *
 * Step 2 — Add the Apps Script
 *   Extensions → Apps Script → replace ALL existing code with the script below.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 *
 *  function getSheet(name) {
 *    return SpreadsheetApp.getActiveSpreadsheet().getSheetByName(name);
 *  }
 *
 *  // Find a Guestbook row by ID (col B). Returns the 1-based row number or -1.
 *  function findRowById(sheet, msgId) {
 *    var data = sheet.getDataRange().getValues();
 *    for (var i = 1; i < data.length; i++) {
 *      if (String(data[i][1]) === String(msgId)) return i + 1;
 *    }
 *    return -1;
 *  }
 *
 *  // Wrap any JSON string in a CORS-safe response.
 *  // Apps Script GET requests are redirected by Google, which strips CORS headers.
 *  // Returning via HtmlService with Content-Type text/plain bypasses this.
 *  function jsonResponse(obj) {
 *    return ContentService
 *      .createTextOutput(JSON.stringify(obj))
 *      .setMimeType(ContentService.MimeType.TEXT);
 *  }
 *
 *  function doPost(e) {
 *    var data = JSON.parse(e.postData.contents);
 *    var ts   = new Date().toISOString();
 *
 *    if (data.action === 'rsvp') {
 *      getSheet('RSVP').appendRow([
 *        ts, data.name, data.phone, data.attendance,
 *        data.guests, data.dietary, data.message
 *      ]);
 *
 *    } else if (data.action === 'guestbook') {
 *      getSheet('Guestbook').appendRow([
 *        ts, data.id, data.name, data.message, 0, ''
 *      ]);
 *
 *    } else if (data.action === 'like') {
 *      var sheet    = getSheet('Guestbook');
 *      var msgId    = String(data.msgId  || '').trim();
 *      var deviceId = String(data.deviceId || '').trim();
 *      if (!msgId || !deviceId) return jsonResponse({ status: 'error', msg: 'Missing params' });
 *      var rowNum = findRowById(sheet, msgId);
 *      if (rowNum === -1) return jsonResponse({ status: 'error', msg: 'Message not found' });
 *      var likesCell   = sheet.getRange(rowNum, 5);
 *      var likedByCell = sheet.getRange(rowNum, 6);
 *      var likes       = parseInt(likesCell.getValue()) || 0;
 *      var likedByRaw  = String(likedByCell.getValue() || '');
 *      var likedByArr  = likedByRaw ? likedByRaw.split(',') : [];
 *      var idx         = likedByArr.indexOf(deviceId);
 *      var liked;
 *      if (idx === -1) { likedByArr.push(deviceId); likes++; liked = true; }
 *      else { likedByArr.splice(idx, 1); likes = Math.max(0, likes - 1); liked = false; }
 *      likesCell.setValue(likes);
 *      likedByCell.setValue(likedByArr.join(','));
 *      return jsonResponse({ status: 'ok', likes: likes, liked: liked });
 *
 *    } else if (data.action === 'gallery') {
 *      getSheet('Gallery').appendRow([ts, data.category, data.imageUrl]);
 *
 *    } else {
 *      return jsonResponse({ status: 'error', msg: 'Unknown action' });
 *    }
 *
 *    return jsonResponse({ status: 'ok' });
 *  }
 *
 *  function doGet(e) {
 *    var action   = e.parameter.action;
 *    var deviceId = String(e.parameter.deviceId || '').trim();
 *
 *    if (action === 'guestbook') {
 *      var rows = getSheet('Guestbook').getDataRange().getValues();
 *      var messages = rows.slice(1).map(function(row) {
 *        var likedByArr = String(row[5] || '') ? String(row[5]).split(',') : [];
 *        return {
 *          id:        String(row[1]),
 *          time:      row[0],
 *          name:      row[2],
 *          message:   row[3],
 *          likes:     parseInt(row[4]) || 0,
 *          likedByMe: deviceId ? likedByArr.indexOf(deviceId) !== -1 : false
 *        };
 *      }).reverse();
 *      return jsonResponse(messages);
 *    }
 *
 *    if (action === 'gallery') {
 *      var rows = getSheet('Gallery').getDataRange().getValues();
 *      var photos = rows.slice(1).map(function(row) {
 *        return { time: row[0], category: row[1], imageUrl: row[2] };
 *      }).reverse();
 *      return jsonResponse(photos);
 *    }
 *
 *    return jsonResponse({ status: 'error', msg: 'Unknown action' });
 *      .createTextOutput(JSON.stringify({ status: 'error', msg: 'Unknown action' }))
 *      .setMimeType(ContentService.MimeType.JSON);
 *  }
 *
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Step 3 — Deploy
 *   Deploy → New deployment → Type: Web App
 *   Execute as: Me | Who has access: Anyone
 *   Copy the Web App URL.
 *   (If updating an existing deployment: Deploy → Manage deployments →
 *    Edit → New version → Deploy)
 *
 * Step 4 — Set the URL
 *   Paste the URL into js/config.js — one value powers all three features.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 */
 

import { initCountdown }  from './countdown.js';
import { initGallery }    from './gallery.js';
import { initGuestbook }  from './guestbook.js';
import { initScroll }     from './scroll.js';
import { SCRIPT_URL }     from './config.js';

// ─── Component manifest ──────────────────────────────────────────────────────
const COMPONENTS = [
  { name: 'hero',       css: 'hero.css'      },
  { name: 'event',      css: 'event.css'     },
  { name: 'countdown',  css: 'countdown.css' },
  { name: 'location',   css: 'location.css'  },
  { name: 'rsvp',       css: 'rsvp.css'      },
  { name: 'gallery',    css: 'gallery.css'   },
  { name: 'guestbook',  css: 'guestbook.css' },
  { name: 'footer',     css: 'footer.css'    },
];

// ─── CSS loader ──────────────────────────────────────────────────────────────
function loadCSS(href) {
  if (document.querySelector(`link[href="${href}"]`)) return;
  const link = document.createElement('link');
  link.rel = 'stylesheet';
  link.href = href;
  document.head.appendChild(link);
}

// ─── Component loader ────────────────────────────────────────────────────────
async function loadComponent(name) {
  const res = await fetch(`components/${name}.html`);
  if (!res.ok) throw new Error(`Failed to load component: ${name} (${res.status})`);
  return res.text();
}

// ─── Sequential component insertion ─────────────────────────────────────────
async function loadAllComponents(app) {
  for (const comp of COMPONENTS) {
    try {
      loadCSS(`css/${comp.css}`);
      const html = await loadComponent(comp.name);
      app.insertAdjacentHTML('beforeend', html);
    } catch (err) {
      console.error(err);
    }
  }
}

// ─── RSVP modal open/close ────────────────────────────────────────────────────
function initRSVPModal() {
  const modal    = document.getElementById('rsvp-modal');
  const openBtn  = document.getElementById('event-rsvp-open-btn');
  const closeBtn = document.getElementById('rsvp-modal-close');
  const backdrop = document.getElementById('rsvp-modal-backdrop');

  if (!modal) return;

  function openModal() {
    modal.removeAttribute('hidden');
    document.body.style.overflow = 'hidden';
    closeBtn?.focus();
  }
  function closeModal() {
    modal.setAttribute('hidden', '');
    document.body.style.overflow = '';
    openBtn?.focus();
  }

  openBtn?.addEventListener('click', (e) => { e.preventDefault(); openModal(); });
  closeBtn?.addEventListener('click', closeModal);
  backdrop?.addEventListener('click', closeModal);
  document.addEventListener('keydown', (e) => {
    if (!modal.hasAttribute('hidden') && e.key === 'Escape') closeModal();
  });
}

// ─── RSVP form ───────────────────────────────────────────────────────────────
function initRSVP() {
  const form       = document.getElementById('rsvp-form');
  const submitBtn  = document.getElementById('rsvp-submit-btn');
  const successBox = document.getElementById('rsvp-success');
  const successMsg = document.getElementById('rsvp-success-msg');
  const resetBtn   = document.getElementById('rsvp-reset-btn');
  const msgArea    = document.getElementById('rsvp-message');
  const charCount  = document.getElementById('rsvp-msg-count');

  if (!form) return;

  // Char counter
  msgArea?.addEventListener('input', () => {
    const len = msgArea.value.length;
    charCount.textContent = `${len} / 500`;
    charCount.style.color = len > 480 ? '#e57373' : 'rgba(255,255,255,0.4)';
  });

  // Hide guest count when declining
  document.querySelectorAll('input[name="attendance"]').forEach(radio => {
    radio.addEventListener('change', () => {
      const gc = document.getElementById('guest-count-group');
      const dg = document.getElementById('dietary-group');
      const mg = document.getElementById('message-group');
      const isNo = radio.value === 'no';
      if (gc) gc.style.display = isNo ? 'none' : '';
      if (dg) dg.style.display = isNo ? 'none' : '';
      if (mg) mg.style.display = isNo ? 'none' : '';
    });
  });

  // Validate helper
  function showError(id, msg) {
    const el = document.getElementById(id);
    if (el) el.textContent = msg;
  }
  function clearErrors() {
    document.querySelectorAll('.form-error').forEach(el => (el.textContent = ''));
    document.querySelectorAll('.invalid').forEach(el => el.classList.remove('invalid'));
  }

  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    clearErrors();

    const nameVal     = document.getElementById('rsvp-name')?.value.trim() || '';
    const phoneVal    = document.getElementById('rsvp-phone')?.value.trim() || '';
    const attVal      = document.querySelector('input[name="attendance"]:checked')?.value || '';
    const guestsVal   = document.getElementById('rsvp-guests')?.value || '';
    const dietaryVal  = document.getElementById('rsvp-dietary')?.value.trim() || '';
    const messageVal  = msgArea?.value.trim() || '';

    let valid = true;

    if (nameVal.length < 2) {
      showError('rsvp-name-err', 'Sila masukkan nama penuh anda.');
      document.getElementById('rsvp-name')?.classList.add('invalid');
      valid = false;
    }
    if (!attVal) {
      showError('rsvp-att-err', 'Sila pilih kehadiran anda.');
      valid = false;
    }
    if (!valid) return;

    // Loading state
    submitBtn.disabled = true;
    submitBtn.querySelector('.btn-text')?.classList.add('hidden');
    submitBtn.querySelector('.btn-loading')?.classList.remove('hidden');

    const payload = {
      action:     'rsvp',
      name:       nameVal,
      phone:      phoneVal,
      attendance: attVal,
      guests:     attVal === 'yes' ? guestsVal : '',
      dietary:    attVal === 'yes' ? dietaryVal : '',
      message:    attVal === 'yes' ? messageVal : '',
    };

    // Submit to Google Sheets if configured, otherwise local demo
    if (SCRIPT_URL) {
      try {
        await fetch(SCRIPT_URL, {
          method:  'POST',
          mode:    'no-cors',
          headers: { 'Content-Type': 'text/plain' },
          body:    JSON.stringify(payload),
        });
        // no-cors returns opaque response — assume success if no throw
      } catch (err) {
        console.error('[RSVP] Submit error:', err);
        // Still show success to user — don't leave them hanging on a network blip
      }
    }

    submitBtn.disabled = false;
    submitBtn.querySelector('.btn-text')?.classList.remove('hidden');
    submitBtn.querySelector('.btn-loading')?.classList.add('hidden');

    form.classList.add('hidden');
    successBox.classList.remove('hidden');

    const message = attVal === 'yes'
      ? `Kami telah menerima RSVP anda dan tidak sabar untuk meraikan bersama anda, ${nameVal}!`
      : `Kami kesal anda tidak dapat hadir, ${nameVal}. Anda tetap dalam hati kami!`;
    if (successMsg) successMsg.textContent = message;

    // Auto-close modal after 3s on success
    setTimeout(() => {
      const modal = document.getElementById('rsvp-modal');
      if (modal) { modal.setAttribute('hidden', ''); document.body.style.overflow = ''; }
    }, 3000);
  });

  resetBtn?.addEventListener('click', () => {
    form.classList.remove('hidden');
    successBox.classList.add('hidden');
    form.reset();
    clearErrors();
    submitBtn.disabled = false;
    submitBtn.querySelector('.btn-text')?.classList.remove('hidden');
    submitBtn.querySelector('.btn-loading')?.classList.add('hidden');
    if (charCount) charCount.textContent = '0 / 500';
    // Restore hidden groups on reset
    ['guest-count-group', 'dietary-group', 'message-group'].forEach(id => {
      const el = document.getElementById(id);
      if (el) el.style.display = '';
    });
  });
}

// ─── Back to top ─────────────────────────────────────────────────────────────
function initBackToTop() {
  const btn = document.getElementById('back-to-top');
  if (!btn) return;
  window.addEventListener('scroll', () => {
    btn.classList.toggle('visible', window.scrollY > 500);
  }, { passive: true });
  btn.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));
}

// ─── Footer year ─────────────────────────────────────────────────────────────
function initFooterYear() {
  const el = document.getElementById('footer-year');
  if (el) el.textContent = new Date().getFullYear();
}

// ─── Nav highlight on scroll ─────────────────────────────────────────────────
function initActiveNav() {
  const sections = ['hero','event','countdown','gallery','location','guestbook'];
  const links    = document.querySelectorAll('.footer-nav a');

  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const id = entry.target.id;
        links.forEach(l => {
          l.style.color = l.getAttribute('href') === `#${id}`
            ? 'var(--gold-light)'
            : '';
        });
      }
    });
  }, { threshold: 0.4 });

  sections.forEach(id => {
    const el = document.getElementById(id);
    if (el) observer.observe(el);
  });
}

// ─── Loading screen ──────────────────────────────────────────────────────────
function hideLoadingScreen() {
  const ls = document.getElementById('loading-screen');
  if (!ls) return;
  ls.classList.add('hidden');
  // Remove from DOM after transition
  ls.addEventListener('transitionend', () => ls.remove(), { once: true });
}

// ─── Bootstrap ───────────────────────────────────────────────────────────────
(async function bootstrap() {
  const app = document.getElementById('app');
  if (!app) return;

  await loadAllComponents(app);

  // Small tick to allow DOM paint before initialising
  requestAnimationFrame(() => {
    initScroll();
    initCountdown();
    initGallery();
    initGuestbook();
    initRSVPModal();
    initRSVP();
    initBackToTop();
    initFooterYear();
    initActiveNav();
    hideLoadingScreen();
  });
})();
